[package]
name = "fastsync"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.153"
borsh = { version = "1.3.1", features = ["derive"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
